/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package contenido;

import informacion.Habitaciones;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import BDD.ABC_Habitaciones;
import informacion.MySqlConn;
import informacion.Registro;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
/**
 *
 * @author kapu
 */
public class CheckIn extends javax.swing.JInternalFrame {

    /**
     * Creates new form CheckIn
     */
    MySqlConn conn= new MySqlConn();
     ArrayList <Registro> lista = new ArrayList();
     private int precio1=900;
     private int precio2=1200;
     private int precio3=1800;
       private int extra=200;
     private int tipo1 =1;
     private int tipo2 =2;
     private int tipo3 =3;
     
    // String dia2,mes2,anio2;
     
     
        
        
    public CheckIn() {
       
        initComponents();
         fecha();
         totalhabit();
         this.jTextFieldDias.setEnabled(false);
    }
    
    public void totalhabit(){
        String registro="registro";
        String query = "select * from registro";
        this.conn.Consult(query);
        int n=0;
        //int n2=30;
        int dispo=0;
        try{
            this.conn.rs.last();
            n=this.conn.rs.getRow();
            this.conn.rs.first();
          //  n=n2;
           // System.out.println(n);
            if(n==30){
             this.jLabelDis.setText("HOTEL LLENO");
             this.jButtonGuardar.setEnabled(false);
             this.jTextFieldNomCliente.setEnabled(false);
             this.jTextFieldHuespedes.setEnabled(false);
             
            }else{
            this.jLabelDis.setText(String.valueOf(30-n));
            }
            }catch(Exception e){
            System.out.println("Error 1...");
        }
        
    }
    
    
    public void fecha(){
        Calendar fecha = new GregorianCalendar();  
     
        int anio = fecha.get(Calendar.YEAR);
        int mes = fecha.get(Calendar.MONTH);
        int dia = fecha.get(Calendar.DAY_OF_MONTH);  
       mes+=1;
        String dia2=String.valueOf(anio);
        String mes2=String.valueOf(mes);
        String anio2=String.valueOf(dia);
        
        Calendar fechanueva=Calendar.getInstance();
        fechanueva.set(anio,mes,dia);
        
        SimpleDateFormat dateformat=new SimpleDateFormat("dd-MM-YYYY");
        String date = dateformat.format(fechanueva.getTime());
        this.jLabelFechaIn.setText(date);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNomCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCiudad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxHabitacion = new javax.swing.JComboBox();
        jButtonGuardar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabelFechaIn = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxExtra = new javax.swing.JComboBox();
        jTextFieldDias = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonChecar = new javax.swing.JButton();
        jTextFieldHuespedes = new javax.swing.JTextField();
        jLabeldispo = new javax.swing.JLabel();
        jLabeltipo = new javax.swing.JLabel();
        jLabelExtra = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabelDis = new javax.swing.JLabel();
        jSpinnerExtra = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabelDispo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 153, 153));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CheckIn");
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(747, 402));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabelNombre.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelNombre.setText("Nombre");

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel1.setText("Ciudad");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel2.setText("Habitacion");

        jComboBoxHabitacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114", "115", "116", "117", "118", "119", "120", "121", "122", "123", "124", "125", "126", "127", "128", "129", "130" }));
        jComboBoxHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxHabitacionActionPerformed(evt);
            }
        });

        jButtonGuardar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel6.setText("Fecha entrada:");

        jLabelFechaIn.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelFechaIn.setText("En espera");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel8.setText("Total de personas: ");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel7.setText("Numero de dias");

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel9.setText("Personas Extra");

        jComboBoxExtra.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2" }));
        jComboBoxExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxExtraActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel3.setText("Habitaciones disponibles");

        jButtonChecar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButtonChecar.setText("Checar");
        jButtonChecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChecarActionPerformed(evt);
            }
        });

        jTextFieldHuespedes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldHuespedesKeyReleased(evt);
            }
        });

        jLabeldispo.setText("En espera...");

        jLabeltipo.setText("En espera...");

        jLabelExtra.setText("En espera...");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel4.setText("Hab. Disponibles");

        jLabelDis.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelDis.setText("En espera");

        jSpinnerExtra.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel5.setText("Disponibilidad: ");

        jLabelDispo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelDispo.setText("En espera...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(409, 409, 409)
                                .addComponent(jLabelExtra))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabel6)
                                .addGap(28, 28, 28)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldHuespedes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(40, 40, 40)
                        .addComponent(jComboBoxExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(259, 259, 259))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonGuardar)
                                .addGap(42, 42, 42)
                                .addComponent(jButton2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(jTextFieldDias, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jSpinnerExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(17, 17, 17))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelDispo)
                                            .addComponent(jComboBoxHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabeltipo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addGap(29, 29, 29)
                                .addComponent(jButtonChecar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabelNombre)
                                .addGap(32, 32, 32)
                                .addComponent(jTextFieldNomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelFechaIn)
                                .addGap(126, 126, 126)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(51, 51, 51)
                                .addComponent(jLabelDis))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabeldispo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelDis)
                    .addComponent(jLabelFechaIn))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBoxHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabeltipo)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonChecar)
                            .addComponent(jLabel3))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jComboBoxExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabelDispo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldHuespedes))))
                .addComponent(jLabelExtra)
                .addGap(1, 1, 1)
                .addComponent(jLabeldispo)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jSpinnerExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonGuardar)
                                    .addComponent(jButton2))
                                .addGap(116, 116, 116))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jTextFieldDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel6)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        
        
        String nombre,ciudad;
        int piso=0, habi,totpersonas,extra;
        int tipo_habi=0,dias=0;
        String habit="";
        int tarifa;
        
       // this.jComboBoxHabitacion.setModel();
        
        nombre=jTextFieldNomCliente.getText().trim();
        ciudad=jTextFieldCiudad.getText().trim();
       // piso=jComboBoxPiso.getSelectedIndex();
        
        //piso=Integer.valueOf(jComboBoxPiso.getSelectedItem().toString());
        //habi=jComboBoxHabitacion.getSelectedIndex();
        habi=Integer.valueOf(jComboBoxHabitacion.getSelectedItem().toString());
        //System.out.println(habi);
        if(habi<=115){
            piso=1;
        }else{
            piso=2;
        }
        totpersonas=Integer.valueOf(this.jTextFieldHuespedes.getText().trim());
        extra=jComboBoxExtra.getSelectedIndex();
        
        //dias=Integer.valueOf(this.jTextFieldDias.getText().trim());
        dias=Integer.valueOf(this.jSpinnerExtra.getValue().toString());
      
        
        if((habi>=101&&habi<=110)||(habi>=116&&habi<=120)){
            tipo_habi=1;
            habit="Individual";
        }else if((habi>=111&&habi<=113)||(habi>=121&&habi<=126)){
            tipo_habi=2;
            habit="Doble";
        }else{
            tipo_habi=3;
            habit="Familiar";
        }
        
        if(tipo_habi==1){
            tarifa=dias*precio1;
        }else if(tipo_habi==2){
            tarifa=dias*precio2;
        }else{
            tarifa=dias*precio3;
        }
        
      
      
        
        String dia,mes,anio;
        
       
        
        int diafecha=this.jDateChooser1.getCalendar().get(Calendar.DAY_OF_MONTH);
        int mesfecha=this.jDateChooser1.getCalendar().get(Calendar.MONTH);
        int aniofecha=this.jDateChooser1.getCalendar().get(Calendar.YEAR);
        
        dia=String.valueOf(diafecha);
        mes=String.valueOf(mesfecha);
        anio=String.valueOf(aniofecha);
        //instancia del objeto para manipular la fecha
       Calendar fechanueva=Calendar.getInstance();
       //Se agrega la fecha
        fechanueva.set(Integer.parseInt(anio), Integer.parseInt(mes), Integer.parseInt(dia));
        
   
        Calendar fechanueva2=Calendar.getInstance();
        fechanueva2.set(Integer.parseInt(anio), Integer.parseInt(mes), Integer.parseInt(dia));
        
        fechanueva2.add(Calendar.DAY_OF_MONTH, dias);
        
        SimpleDateFormat dateformat=new SimpleDateFormat("yyyy-MM-dd");
        String date = dateformat.format(fechanueva.getTime());
        SimpleDateFormat dateformat2=new SimpleDateFormat("yyyy-MM-dd");
        String date2 = dateformat.format(fechanueva2.getTime());
        
        fechanueva.add(Calendar.DAY_OF_MONTH, dias);
        
        //Aqui dentro esta para el array
        Registro registro = new Registro(nombre,ciudad,habit,piso,habi,totpersonas,extra,dias,tarifa);
        lista.add(registro);
        //System.out.println(lista);
        
        //aqui va para la base de datos
        String parte1 = "Insert into registro (Num_Habitacion, Tipo_Habitacion, Piso, Nombre, Ciudad, Num_Huespedes, Num_HuespedesExtra, Entrada, Dias, salida) VALUES (";
        String parte2 = "'"+habi+"','"+habit+"','"+piso+"','"+nombre+"','"+ciudad+"','"+totpersonas+"','"+extra+"','"+date+"','"+dias+"','"+date2+"')";
        String query = parte1 + parte2;
        int j = this.conn.Update(query); 
        JOptionPane.showMessageDialog(this,"Huesped registrado");
        totalhabit();
        
       new Recibo(habi).setVisible(true); 
        dispose();
        
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonChecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChecarActionPerformed
        // TODO add your handling code here:
        
        // para las habitaciones
       new HabDisponibles().setVisible(true);
        
    }//GEN-LAST:event_jButtonChecarActionPerformed

    private void jTextFieldHuespedesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldHuespedesKeyReleased
        // TODO add your handling code here:
        int personas,habi;
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            personas=Integer.valueOf(this.jTextFieldHuespedes.getText().trim());
            habi=Integer.valueOf(jComboBoxHabitacion.getSelectedItem().toString());
            
            if(habi>=101&&habi<=110||habi>=116&&habi<=120){
                if(personas>1){
                    this.jLabeldispo.setText("Cantidad no disponible");
                    this.jButtonGuardar.setEnabled(false);
                }else{
                    this.jLabeldispo.setText("Cantidad disponible");
                    this.jButtonGuardar.setEnabled(true);
                }
            }else if(habi>=111&&habi<=113||habi>=121&&habi<=126){
                if(personas>2){
                    this.jLabeldispo.setText("Cantidad no disponible");
                    this.jButtonGuardar.setEnabled(false);
                }else{
                    this.jLabeldispo.setText("Cantidad disponible");
                    this.jButtonGuardar.setEnabled(true);
                }
            }else{
              if(personas>4){
                    this.jLabeldispo.setText("Cantidad no disponible");
                    this.jButtonGuardar.setEnabled(false);
                }else{
                    this.jLabeldispo.setText("Cantidad disponible");
                    this.jButtonGuardar.setEnabled(true);
                }  
            }
            
        }
        
    }//GEN-LAST:event_jTextFieldHuespedesKeyReleased

    private void jComboBoxHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxHabitacionActionPerformed
        // TODO add your handling code here:
        int habi=0;
        habi=Integer.valueOf(jComboBoxHabitacion.getSelectedItem().toString());
        
        if(habi>=101&&habi<=110||habi>=116&&habi<=120){
               if(habi>=11&&habi<=110){
                   this.jLabeltipo.setText("Individual en piso 1");
               }else{
                   this.jLabeltipo.setText("Individual en piso 2");
               }
            }else if(habi>=111&&habi<=113||habi>=121&&habi<=126){
               if(habi>=111&&habi<=113){
                   this.jLabeltipo.setText("Doble en piso 1");
               }else{
                   this.jLabeltipo.setText("Doble en piso 2");
               } 
            }else{
                if(habi>=114&&habi<=115){
                   this.jLabeltipo.setText("Familiar en piso 1");
               }else{
                   this.jLabeltipo.setText("Familiar en piso 2");
               }
            }
            
        String query2= "select * from registro where Num_Habitacion= "+"'"+habi+"'";
        this.conn.Consult(query2);
        int n =0;
        boolean band=false;
        try{
            this.conn.rs.last();
            n= this.conn.rs.getRow();
            this.conn.rs.first();
            
        }catch(Exception e){
            System.out.println("No hay datos");
        }
        if(n!=0){
            //Object datos [][]= new Object[n][10];
            for (int i = 0; i < n; i++) {
                try{
                    if(habi==this.conn.rs.getInt(1)){
                        band=true;
                    }
                    this.conn.rs.next();
                }catch(Exception e){
                    System.out.println("Error...");
                }
                
            }
            
        if(band==true){
            this.jLabelDispo.setText("No disponible");
            this.jButtonGuardar.setEnabled(false);
            this.jTextFieldHuespedes.setEnabled(false);
        }else{
            
        }    
  
        }else{
            this.jLabelDispo.setText("Disponible");
            this.jButtonGuardar.setEnabled(true);
            this.jTextFieldHuespedes.setEnabled(true);
        }
        
        
        
    }//GEN-LAST:event_jComboBoxHabitacionActionPerformed

    private void jComboBoxExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxExtraActionPerformed
        // TODO add your handling code here:
        
        this.jLabelExtra.setText("Precio extra de $200 por persona");
        
    }//GEN-LAST:event_jComboBoxExtraActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Registro cancelado");
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonChecar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JComboBox jComboBoxExtra;
    private javax.swing.JComboBox jComboBoxHabitacion;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDis;
    private javax.swing.JLabel jLabelDispo;
    private javax.swing.JLabel jLabelExtra;
    private javax.swing.JLabel jLabelFechaIn;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabeldispo;
    private javax.swing.JLabel jLabeltipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerExtra;
    private javax.swing.JTextField jTextFieldCiudad;
    private javax.swing.JTextField jTextFieldDias;
    private javax.swing.JTextField jTextFieldHuespedes;
    private javax.swing.JTextField jTextFieldNomCliente;
    // End of variables declaration//GEN-END:variables
}
