
package contenido;

import informacion.MySqlConn;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class CheckOut extends javax.swing.JInternalFrame {

    private int precio1 = 900;
    private int precio2 = 1200;
    private int precio3 = 1800;
    private int extra = 200;

    private int tipo1 = 1;
    private int tipo2 = 2;
    private int tipo3 = 3;

    MySqlConn conn = new MySqlConn();

    public CheckOut() {
        initComponents();
        fecha();
    }

    public void fecha() {
        Calendar fecha = new GregorianCalendar();
        String fechaout = "";
        int anio = fecha.get(Calendar.YEAR);
        int mes = fecha.get(Calendar.MONTH);
        int dia = fecha.get(Calendar.DAY_OF_MONTH);
        mes += 1;
        String dia2 = String.valueOf(anio);
        String mes2 = String.valueOf(mes);
        String anio2 = String.valueOf(dia);

        Calendar fechanueva = Calendar.getInstance();
        fechanueva.set(anio, mes, dia);

        SimpleDateFormat dateformat = new SimpleDateFormat("dd-MM-YYYY");
        String date = dateformat.format(fechanueva.getTime());
        this.jLabelFechafin.setText(date);
    }

    public void busqueda() {
        String query = "select * from registro where Num_Habitacion = " + "'"
                + Integer.valueOf(this.jTextFieldHabi.getText()) + "'";
        this.conn.Consult(query);
        int n = 0;
        try {
            this.conn.rs.last();
            n = this.conn.rs.getRow();
            this.conn.rs.first();
        } catch (Exception e) {
            System.out.println("Error 1...");
        }
        if (n != 0) {
            System.out.println("n  " + n);
            Object datos[][] = new Object[n][10];
            for (int i = 0; i < n; i++) {
                try {
                    datos[i][0] = this.conn.rs.getInt(1);
                    datos[i][1] = this.conn.rs.getString(2);
                    datos[i][2] = this.conn.rs.getInt(3);
                    datos[i][3] = this.conn.rs.getString(4);
                    datos[i][4] = this.conn.rs.getString(5);
                    datos[i][5] = this.conn.rs.getInt(6);
                    datos[i][6] = this.conn.rs.getInt(7);
                    datos[i][7] = this.conn.rs.getString(8);
                    datos[i][8] = this.conn.rs.getInt(9);
                    datos[i][9] = this.conn.rs.getString(10);

                    this.conn.rs.next();
                } catch (Exception e) {
                    System.out.println("Error 2...");
                }

            }
            String columnas[] = {"Habitacion", "Tipo", "Piso", "Nombre", "Ciudad", "Num_Huespedes", "Huesped ex", "Entrada", "Dias"};
            jTableCheckOut.setModel(new DefaultTableModel(datos, columnas));
            System.out.println("Tabla lista");
        } else {
            JOptionPane.showMessageDialog(this, "No hay datos...");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldHabi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCheckOut = new javax.swing.JTable();
        jButtonCheckOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelFechafin = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CheckOut");
        setPreferredSize(new java.awt.Dimension(747, 402));

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel1.setText("Num. Habitacion");

        jScrollPane1.setViewportView(jTableCheckOut);

        jButtonCheckOut.setText("CHECK OUT");
        jButtonCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckOutActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel2.setText("Fecha");

        jLabelFechafin.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelFechafin.setText("En espera...");

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jButtonCheckOut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jTextFieldHabi, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButtonBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabelFechafin)
                .addGap(153, 153, 153))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldHabi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelFechafin)
                    .addComponent(jButtonBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButtonCheckOut)
                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        busqueda();

    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckOutActionPerformed
//System.out.println("Entre");

        String hab = this.jTextFieldHabi.getText().trim();
        String fechaout = "", fechain = "";
        String query = "select * from registro where Num_Habitacion= " + "'" + hab + "'";
        String query2;
        int pisod = 0, tipopiso, dias = 0, extra = 0, habi = 0;
        String tipohab = "";
        String nombre = "";
        int pagotot = 0;

        int cuentatot = 0;

        this.conn.Consult(query);
        int n = 0;

        try {
            this.conn.rs.last();
            n = this.conn.rs.getRow();
            this.conn.rs.first();

        } catch (Exception e) {
            System.out.println("No hay datos");
        }
        if (n != 0) {
            Object datos[][] = new Object[n][10];
            for (int i = 0; i < n; i++) {
                try {
                    datos[i][0] = this.conn.rs.getInt(1);
                    habi = this.conn.rs.getInt(1);
                    datos[i][1] = this.conn.rs.getString(2);
                    tipohab = this.conn.rs.getString(2);
                    System.out.println(tipohab);
                    datos[i][2] = this.conn.rs.getInt(3);
                    pisod = this.conn.rs.getInt(3);

                    datos[i][3] = this.conn.rs.getString(4);
                    nombre = this.conn.rs.getString(4);
                    datos[i][4] = this.conn.rs.getString(5);
                    datos[i][5] = this.conn.rs.getInt(6);
                    datos[i][6] = this.conn.rs.getInt(7);
                    extra = this.conn.rs.getInt(7);
                    datos[i][7] = this.conn.rs.getString(8);
                    fechain = this.conn.rs.getString(8);
                    datos[i][8] = this.conn.rs.getInt(9);
                    dias = this.conn.rs.getInt(9);
                    datos[i][8] = this.conn.rs.getString(10);
                    fechaout = this.conn.rs.getString(10);

                    this.conn.rs.next();
                } catch (Exception e) {
                    System.out.println("Error...");
                }

            }

        }

        if (habi >= 1 && habi <= 10 || habi >= 16 && habi <= 20) {
            cuentatot = precio1 * dias;
            cuentatot = cuentatot + (extra * dias);
        } else if (habi >= 11 && habi <= 13 || habi >= 21 && habi <= 26) {
            cuentatot = precio2 * dias;
            cuentatot = cuentatot + (extra * dias);
        } else {
            cuentatot = precio3 * dias;
            cuentatot = cuentatot + (extra * dias);
        }

         //Apartado de calculo de la cuenta
        String parte1 = "Insert into historial (nombre, habitacion, ingreso, salida, pago_tot) VALUES (";
        String parte2 = "'" + nombre + "','" + habi + "','" + fechain + "','" + fechaout + "','" + cuentatot + "')";
        query2 = parte1 + parte2;
        this.conn.Update(query2);
        System.out.println(nombre);

        if (hab.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Numero de habitacion vacio");
        } else {

            query = "delete from registro where Num_Habitacion= " + "'" + hab + "'";//completa sentencia Mysql
            int j = this.conn.Update(query);
            if (j > 0) {
                JOptionPane.showMessageDialog(this, "Baja confirmada");
            } else {
                JOptionPane.showMessageDialog(this, "No hay seleccion de huesped");
            }

            // JOptionPane.showMessageDialog(this, "A pagar"+cuentatot);
        }
                   // TODO add your handling code here:


    }//GEN-LAST:event_jButtonCheckOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCheckOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFechafin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCheckOut;
    private javax.swing.JTextField jTextFieldHabi;
    // End of variables declaration//GEN-END:variables
}
