
package contenido;

import clasesinternas.*;
import consultas.Consulta3;
import informacion.MySqlConn;
import informacion.Servicio;
import java.applet.AudioClip;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;


public class Menu extends javax.swing.JFrame {
    AudioClip Sonido;
    
    
    MySqlConn conn=new MySqlConn();
    public Menu() {
        initComponents();
        musicaInicializar();
        this.setLocationRelativeTo(this);                 
    }
    
    
    
    public void musicaInicializar(){
        Sonido = java.applet.Applet.newAudioClip(getClass().getResource("/musica/Torero.wav"));
        Sonido.play();
        ImageIcon imagen = new ImageIcon(getClass().getResource("/imagenes/bocina1.png"));
        Image conversion = imagen.getImage();
        Image tam = conversion.getScaledInstance(35, 35, Image.SCALE_SMOOTH);
        ImageIcon imagenRe = new ImageIcon(tam);
        this.jLabelReproducirMusica.setIcon(imagenRe);
        imagen = new ImageIcon(getClass().getResource("/imagenes/bocina2.png"));
        conversion = imagen.getImage();
        tam = conversion.getScaledInstance(35, 35, Image.SCALE_SMOOTH);
        ImageIcon imagenDe = new ImageIcon(tam);
        this.jLabelDetenerMusica.setIcon(imagenDe);
        this.jLabelReproducirMusica.setVisible(false);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneEscritorio = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(new ImageIcon(getClass().getResource("/imagenes/FondoPantalla.jpg")).getImage(),0,0,getWidth(),getHeight(),this);
            }
        };
        jPanel2 = new javax.swing.JPanel();
        jLabelReproducirMusica = new javax.swing.JLabel();
        jLabelDetenerMusica = new javax.swing.JLabel();
        jButtonIngresos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemEntradas = new javax.swing.JMenuItem();
        jMenuItemSalidas = new javax.swing.JMenuItem();
        jMenuItemCambios = new javax.swing.JMenuItem();
        jMenuItemHuespedes = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemGaleria = new javax.swing.JMenuItem();
        jMenuItemCon3 = new javax.swing.JMenuItem();
        jMenuItemCon4 = new javax.swing.JMenuItem();
        jMenuItemCon5 = new javax.swing.JMenuItem();
        jMenuItemCon6 = new javax.swing.JMenuItem();
        jMenuItemCon8 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItemCon12 = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPaneEscritorio.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(252, 210, 234));
        jPanel2.setForeground(new java.awt.Color(0, 51, 153));

        jLabelReproducirMusica.setBackground(new java.awt.Color(255, 255, 255));
        jLabelReproducirMusica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReproducirMusica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelReproducirMusicaMouseClicked(evt);
            }
        });

        jLabelDetenerMusica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDetenerMusicaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelDetenerMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelReproducirMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabelDetenerMusica, jLabelReproducirMusica});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelReproducirMusica)
                    .addComponent(jLabelDetenerMusica)))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabelDetenerMusica, jLabelReproducirMusica});

        jButtonIngresos.setText("Ingresos Totales");
        jButtonIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPaneEscritorioLayout = new javax.swing.GroupLayout(jDesktopPaneEscritorio);
        jDesktopPaneEscritorio.setLayout(jDesktopPaneEscritorioLayout);
        jDesktopPaneEscritorioLayout.setHorizontalGroup(
            jDesktopPaneEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneEscritorioLayout.createSequentialGroup()
                .addGap(0, 669, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneEscritorioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonIngresos)
                .addGap(19, 19, 19))
        );
        jDesktopPaneEscritorioLayout.setVerticalGroup(
            jDesktopPaneEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneEscritorioLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 339, Short.MAX_VALUE)
                .addComponent(jButtonIngresos)
                .addContainerGap())
        );
        jDesktopPaneEscritorio.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneEscritorio.setLayer(jButtonIngresos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setText("Menu");

        jMenuItemEntradas.setText("Entradas");
        jMenuItemEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEntradasActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemEntradas);

        jMenuItemSalidas.setText("Salidas");
        jMenuItemSalidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalidasActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSalidas);

        jMenuItemCambios.setText("Cambios");
        jMenuItemCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCambiosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCambios);

        jMenuItemHuespedes.setText("Huespedes");
        jMenuItemHuespedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHuespedesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemHuespedes);

        jMenuItem1.setText("Servicios extra");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenu2.setText("Consultas");

        jMenuItemGaleria.setText("Galeria");
        jMenuItemGaleria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGaleriaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemGaleria);

        jMenuItemCon3.setText("Ocupacion por habitacion");
        jMenuItemCon3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCon3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemCon3);

        jMenuItemCon4.setText("Total de habitaciones");
        jMenuItemCon4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCon4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemCon4);

        jMenuItemCon5.setText("Ocupacion del hotel");
        jMenuItemCon5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCon5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemCon5);

        jMenuItemCon6.setText("Precios de habitacion");
        jMenuItemCon6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCon6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemCon6);

        jMenuItemCon8.setText("Buscar huesped");
        jMenuItemCon8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCon8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemCon8);

        jMenuItem2.setText("Huespedes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItemCon12.setText("Personas con servicios");
        jMenuItemCon12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCon12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemCon12);

        jMenu1.add(jMenu2);

        jMenuBar1.add(jMenu1);

        jMenuSalir.setText("Salir");
        jMenuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelDetenerMusicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDetenerMusicaMouseClicked
        // TODO add your handling code here:
        Sonido.stop();
        this.jLabelDetenerMusica.setVisible(false);
        this.jLabelReproducirMusica.setVisible(true);
    }//GEN-LAST:event_jLabelDetenerMusicaMouseClicked

    private void jLabelReproducirMusicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReproducirMusicaMouseClicked
        // TODO add your handling code here:
        Sonido.play();
        this.jLabelDetenerMusica.setVisible(true);
        this.jLabelReproducirMusica.setVisible(false);
    }//GEN-LAST:event_jLabelReproducirMusicaMouseClicked

    private void jMenuItemEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEntradasActionPerformed
         Sonido.stop();
        CheckIn entrada = new CheckIn();
        this.jDesktopPaneEscritorio.add(entrada);
        entrada.show();
    }//GEN-LAST:event_jMenuItemEntradasActionPerformed

    private void jMenuItemSalidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalidasActionPerformed
        Sonido.stop();
        CheckOut out = new CheckOut();
        this.jDesktopPaneEscritorio.add(out);
        out.show();
        
    }//GEN-LAST:event_jMenuItemSalidasActionPerformed

    private void jMenuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSalirMouseClicked
        Sonido.stop();
        new PortadaHotel().setVisible(true); //Opcional
        this.dispose();
    }//GEN-LAST:event_jMenuSalirMouseClicked

    private void jMenuItemGaleriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGaleriaActionPerformed
        Galeria gal = new Galeria();
        this.jDesktopPaneEscritorio.add(gal);
        gal.show();
    }//GEN-LAST:event_jMenuItemGaleriaActionPerformed

    private void jMenuItemHuespedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHuespedesActionPerformed
        // TODO add your handling code here:
        Huespedes hue= new Huespedes();
        this.jDesktopPaneEscritorio.add(hue);
        hue.show();
        
    }//GEN-LAST:event_jMenuItemHuespedesActionPerformed

    private void jButtonIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresosActionPerformed
        // TODO add your handling code here:
       //falta 
        dispose();
        
    }//GEN-LAST:event_jButtonIngresosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
         Servicios ser= new Servicios();
        this.jDesktopPaneEscritorio.add(ser);
        ser.show();
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemCon3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCon3ActionPerformed
     consulta3();
     
    }//GEN-LAST:event_jMenuItemCon3ActionPerformed

    private void jMenuItemCon4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCon4ActionPerformed
     consulta4();
    }//GEN-LAST:event_jMenuItemCon4ActionPerformed

    private void jMenuItemCon5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCon5ActionPerformed
        // TODO add your handling code here:
        consulta5();
    }//GEN-LAST:event_jMenuItemCon5ActionPerformed

    private void jMenuItemCon6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCon6ActionPerformed
        // TODO add your handling code here:
        consulta6();
        
    }//GEN-LAST:event_jMenuItemCon6ActionPerformed

    private void jMenuItemCon8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCon8ActionPerformed
        // TODO add your handling code here:
        consulta8();
    }//GEN-LAST:event_jMenuItemCon8ActionPerformed

    private void jMenuItemCon12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCon12ActionPerformed
        // TODO add your handling code here:
       consulta12();
    }//GEN-LAST:event_jMenuItemCon12ActionPerformed

    private void jMenuItemCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCambiosActionPerformed
        // TODO add your handling code here:
        
        Cambios cam= new Cambios();
        this.jDesktopPaneEscritorio.add(cam);
        cam.show();
        
    }//GEN-LAST:event_jMenuItemCambiosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
     Huespedes hue= new Huespedes();
     this.jDesktopPaneEscritorio.add(hue);
     hue.show();
           
        
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
 public void consulta3(){
        String sen="Individual";
        String dob="Doble";
        String fam="Familiar";
        int senc=0,dobl=0,fami=0;
        //int tot=0;
        String query = "select * from registro";
        this.conn.Consult(query);
        int n=0;
        try{
            this.conn.rs.last();
            n=this.conn.rs.getRow();
            this.conn.rs.first();
        }catch(Exception e){
            System.out.println("Error 1...");
        }
        
        if(n!=0){
            for (int i = 0; i < n; i++) {
                 try{
                    if(this.conn.rs.getString(2).equalsIgnoreCase(sen)){
                        senc=senc+1;
                    }else if(this.conn.rs.getString(2).equalsIgnoreCase(dob)){
                        dobl=dobl+1;
                    }else if(this.conn.rs.getString(2).equalsIgnoreCase(fam)){
                        fami=fami+1;
                    }

                    this.conn.rs.next();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "No hay datos");
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "No hay datos");
        }
       System.out.println(senc+" "+dobl+" "+fami);
       
            DefaultPieDataset data = new DefaultPieDataset();
            data.setValue("Sencilla", senc);
            data.setValue("Doble", dobl);
            data.setValue("Familiar", fami); 
            JFreeChart chart = ChartFactory.createPieChart(
             "Hotel Chayanne\n Ocupacion por tipo de habitacion\n Habitaciones en uso: "+n,data, true, true, false);

            ChartFrame frame = new ChartFrame("CHAYANNE", chart);
            frame.pack();
            frame.setLocationRelativeTo(this);
            frame.setVisible(true);
  
    }
public void consulta4(){
    //total de habitaciones
    String sen="Individual";
        String dob="Doble";
        String fam="Familiar";
        int senc=0,dobl=0,fami=0;
    String query = "select * from habitaciones";
        this.conn.Consult(query);
        int n=0;
        try{
            this.conn.rs.last();
            n=this.conn.rs.getRow();
            this.conn.rs.first();
        }catch(Exception e){
            System.out.println("Error 1...");
        }
        
        if(n!=0){
            for (int i = 0; i < n; i++) {
                 try{
                    if(this.conn.rs.getString(1).equalsIgnoreCase(sen)){
                        senc=this.conn.rs.getInt(2);
                    }else if(this.conn.rs.getString(1).equalsIgnoreCase(dob)){
                        dobl=this.conn.rs.getInt(2);
                    }else if(this.conn.rs.getString(1).equalsIgnoreCase(fam)){
                        fami=this.conn.rs.getInt(2);
                    }

                    this.conn.rs.next();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "No hay datos");
                }
            }
        }
        System.out.println(senc+" "+dobl+" "+fami);
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(senc, "Individual", "Individual");
        dataset.setValue(dobl, "Doble", "Doble");
        dataset.setValue(fami, "Familiar", "Familiar");
    

        JFreeChart chart = ChartFactory.createBarChart3D
        ("Hotel Chayanne","Tipo de habitacion", "Cantidad de habitaciones", 
        dataset, PlotOrientation.HORIZONTAL, true,true, false);
        

        ChartFrame chartFrame = new ChartFrame("CHAYANNE",chart);
        chartFrame.pack();
        chartFrame.setVisible(true);
        chartFrame.setLocationRelativeTo(null);
   
}
public void consulta5(){
     String query = "select * from registro";
        this.conn.Consult(query);
        int n=0,dis=0;
        try{
            this.conn.rs.last();
            n=this.conn.rs.getRow();
            this.conn.rs.first();
        }catch(Exception e){
            System.out.println("Error 1...");
        }
        dis=30-n;
       

       
            DefaultPieDataset data = new DefaultPieDataset();
            data.setValue("Disponible", dis);
            data.setValue("Ocupado", n); 
            JFreeChart chart = ChartFactory.createPieChart(
             "Hotel Chayanne\n Ocupacion del hotel",data, true, true, false);

            ChartFrame frame = new ChartFrame("CHAYANNE", chart);
            frame.pack();
            frame.setLocationRelativeTo(this);
            frame.setVisible(true);
  
    }

 public void consulta6(){
    
    Icon img = new ImageIcon(getClass().getResource("/imagenes/Fondo.jpg"));
    JOptionPane.showMessageDialog(rootPane,"Individual:  $900/dia\n"
                                          +"Doble:  $1200/dia\n"
                                          +"Familiar:  $1800/dia","Mensaje",JOptionPane.PLAIN_MESSAGE,img);
    }    
public void consulta8(){
    
    int habi=0;
    habi=Integer.parseInt(JOptionPane.showInputDialog("Habitacion del huesped: "));
    String query = "select * from registro where Num_Habitacion ="+"'"+habi+"'";
    this.conn.Consult(query);
    String nombre="";
    Icon img = new ImageIcon(getClass().getResource("/imagenes/Logo.png"));
    int n=0;
        try{
            this.conn.rs.last();
            n=this.conn.rs.getRow();
            this.conn.rs.first();
            if(n!=0){
                nombre=this.conn.rs.getString(4);
                JOptionPane.showMessageDialog(rootPane,"Nombre del huesped: "+nombre,"Mensaje",JOptionPane.PLAIN_MESSAGE,img);
            }else{
                JOptionPane.showMessageDialog(rootPane,"Habitacion no ocupada","Mensaje",JOptionPane.PLAIN_MESSAGE,img);
            }
            
        }catch(Exception e){
            System.out.println("Error loco...");
        }
        
      
}  

public void consulta12(){
    //Pide el nombre del huesped e imprime la lista de servicios extra(Spa,Gym,Cafeteria,limpieza,Niñera)
    String nombre=JOptionPane.showInputDialog("Nombre del huesped: ");
    String query = "select * from servicios where Nombre ="+"'"+nombre+"'";
    this.conn.Consult(query);
    Icon img = new ImageIcon(getClass().getResource("/imagenes/Logo.png"));
    int n=0;
    String ser="";
    int aux=0;
        try{
            this.conn.rs.last();
            n=this.conn.rs.getRow();
            this.conn.rs.first();
            if(n!=0){
                 if(this.conn.rs.getInt(3)==1){
                       ser+="Limpieza\n"; 
                       aux=aux+1;
                    }
                    if(this.conn.rs.getInt(4)==1){
                        ser+="Cafeteria\n";
                        aux=aux+1;
                    }
                    if(this.conn.rs.getInt(5)==1){
                        ser+="Spa\n";
                         aux=aux+1; 
                    }
                    if(this.conn.rs.getInt(6)==1){
                        ser+="Gimnasio\n";
                        aux=aux+1;
                    }
                    if(this.conn.rs.getInt(7)==1){
                        ser+="Niñera";
                        aux=aux+1;
                        
                    }
               // System.out.println(n);
                
           if(aux==1)
             JOptionPane.showMessageDialog(rootPane,"El huesped cuenta con el servicio de:\n "+ser,"Mensaje",JOptionPane.PLAIN_MESSAGE,img);   
           else 
             JOptionPane.showMessageDialog(rootPane,"El huesped cuenta con los servicios de:\n "+ser,"Mensaje",JOptionPane.PLAIN_MESSAGE,img);      
           
          
            
            }else{
                JOptionPane.showMessageDialog(rootPane,"Huesped no registrado en el sistema de servicios","Mensaje",JOptionPane.PLAIN_MESSAGE,img);
            }
            
        }catch(Exception e){
            System.out.println("Error loco...");
        }
    
    
    
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIngresos;
    private javax.swing.JDesktopPane jDesktopPaneEscritorio;
    private javax.swing.JLabel jLabelDetenerMusica;
    private javax.swing.JLabel jLabelReproducirMusica;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemCambios;
    private javax.swing.JMenuItem jMenuItemCon12;
    private javax.swing.JMenuItem jMenuItemCon3;
    private javax.swing.JMenuItem jMenuItemCon4;
    private javax.swing.JMenuItem jMenuItemCon5;
    private javax.swing.JMenuItem jMenuItemCon6;
    private javax.swing.JMenuItem jMenuItemCon8;
    private javax.swing.JMenuItem jMenuItemEntradas;
    private javax.swing.JMenuItem jMenuItemGaleria;
    private javax.swing.JMenuItem jMenuItemHuespedes;
    private javax.swing.JMenuItem jMenuItemSalidas;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
