/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clasesinternas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author angyg
 */
public class Galeria extends javax.swing.JInternalFrame {
    
    private String fotos[] = {"Hotel1.jpeg","Hotel2.jpeg","Hotel3.jpeg","HabitacionIndividual.jpg","HabitacionDoble.jpg","HabitacionFamiliar.jpg","Cafeteria.jpg","Gimnasio.jpeg","Piscina.jpg","Spa.jpg"};
    int band = 0;
    
    public Galeria() {
        initComponents();
        contenido();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelImagenes = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonSiguiente = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Galeria");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabelTitulo.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });

        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jButtonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelImagenes, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jButtonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(jButtonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        if(band==fotos.length-1){
            band = 0;
            this.jLabelTitulo.setText("~[Hotel]~");
            this.jLabelImagenes.setIcon(setIcono("/imagenesgaleria/"+fotos[band], jLabelImagenes));
        }else{
            band++;
            if(band == 3)
                this.jLabelTitulo.setText("~[Habitación Individual]~");
            if(band == 4)
                this.jLabelTitulo.setText("~[Habitación Doble]~");
            if(band == 5)
                this.jLabelTitulo.setText("~[Habitación Familiar]~");
            if(band == 6)
                this.jLabelTitulo.setText("~[Cafeteria]~");
            if(band == 7)
                this.jLabelTitulo.setText("~[Gimnasio]~");
            if(band == 8)
                this.jLabelTitulo.setText("~[Piscina]~");
            if(band == 9)
                this.jLabelTitulo.setText("~[Spa]~");
            this.jLabelImagenes.setIcon(setIcono("/imagenesgaleria/"+fotos[band], jLabelImagenes));
        }
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        if(band==0){
            band = 9;
            this.jLabelTitulo.setText("~[Spa]~");
            this.jLabelImagenes.setIcon(setIcono("/imagenesgaleria/"+fotos[band], jLabelImagenes));
        }else{
            band--;
            if(band == 1)
                this.jLabelTitulo.setText("~[Hotel]~");
            if(band == 3)
                this.jLabelTitulo.setText("~[Habitación Individual]~");
            if(band == 4)
                this.jLabelTitulo.setText("~[Habitación Doble]~");
            if(band == 5)
                this.jLabelTitulo.setText("~[Habitación Familiar]~");
            if(band == 6)
                this.jLabelTitulo.setText("~[Cafeteria]~");
            if(band == 7)
                this.jLabelTitulo.setText("~[Gimnasio]~");
            if(band == 8)
                this.jLabelTitulo.setText("~[Piscina]~");
            this.jLabelImagenes.setIcon(setIcono("/imagenesgaleria/"+fotos[band], jLabelImagenes));
        }
    }//GEN-LAST:event_jButtonAtrasActionPerformed
    
    /**/
    
    public void contenido(){
        this.jLabelTitulo.setText("~[Hotel]~");
        this.jButtonAtras.setIcon(setIconBoton("/imagenesgaleria/Flecha1.png", jButtonAtras));
        this.jButtonSiguiente.setIcon(setIconBoton("/imagenesgaleria/Flecha2.png", jButtonSiguiente));
        this.jLabelImagenes.setIcon(setIcono("/imagenesgaleria/Hotel1.jpeg", jLabelImagenes));
    }
    
    public Icon setIcono(String url, JLabel imagen){
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(450, 300, Image.SCALE_DEFAULT));
        return icono;
    }
    
    public Icon setIconBoton(String url, JButton boton){
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(40, 40, Image.SCALE_DEFAULT));
        return icono;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JLabel jLabelImagenes;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
